export enum TournamentEnums {
  LOADINGPAGE = 'LOADINGPAGE',
  SETTINGSPAGE = 'SETTINGSPAGE',
  PLAYERLIST = 'PLAYERLIST',
  SCHEDULE = 'SCHEDULE',
  GAME = 'GAME',
  STARTPAGE = 'STARTPAGE',
}

export enum ArenaEnums {
  LOADINGPAGE = 'LOADINGPAGE',
  SETTINGSPAGE = 'SETTINGSPAGE',
  PLAYERLIST = 'PLAYERLIST',
  GAME = 'GAME',
};
