name: Docker Image CD

on:
  push:
    tags:
      - '*.*.*'
    branches: [ "main", "docker_tags" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        tags: |
          # set latest tag for master branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'docker_tags') }}
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        