# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Checks and docker

on:
  push:
    branches: [ "main", "docker_CI" ]
  pull_request:
    branches: [ "main", "docker_CI" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    
    # TODO: Add and enable tests
    #- name: Run the tests
    #  run: npm test
    - name: Typecheck
      run: npm run typecheck  
    - name: Build
      run: CI='' npm run build

    ##DOCKER##
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      id:   docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


    # TODO: Deploy to site
    # Following guide: https://dev.to/dyarleniber/setting-up-a-ci-cd-workflow-on-github-actions-for-a-react-app-with-github-pages-and-codecov-4hnp
    # - name: Deploy
    #   run: |
    #     git config --global user.name $user_name
    #     git config --global user.email $user_email
    #     git remote set-url origin https://${github_token}@github.com/${repository}
    #     npm run deploy
    #   env:
    #     user_name: 'github-actions[bot]'
    #     user_email: 'github-actions[bot]@users.noreply.github.com'
    #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
    #     repository: ${{ github.repository }}
